SELECT CUSTOMER.cid,CUSTOMER.gender,CUSTOMER.firstname,CUSTOMER.lastname,CUSTOMER.address,CART.cartid,CART.cid,CART.status,CART.remarks,CARTDETAILS.iid,CARTDETAILS.cartid,CARTDETAILS.qty,CARTDETAILS.remarks
FROM CUSTOMER,CART,CARTDETAILS
WHERE CUSTOMER.cid=CART.cid,CART.cartid=CARTDETAILS.cartid