SELECT DISTINCT CUSTOMER.cid,CUSTOMER.firstname,CART.cartid,CART.status,CARTDETAILS.iid,CARTDETAILS.qty,BILL.billid,BILL.amount
FROM CUSTOMER,CART,CARTDETAILS,BILL
WHERE CUSTOMER.cid=CART.cid,CART.cartid=CARTDETAILS.cartid,CARTDETAILS.iid=BILL.iid,BILL.amount<"1000",BILL.amount>"500"
